### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 22 column 5 (char 895)

### ISSUE THREAD

**Issue by DarthKeizer** [woolweaver/tweetStats#11]
When i run the python 3 script i get the following error. Do you know how to fix?

~/tweetStats $ python3 tweetStats.py
0
Traceback (most recent call last):
  File "tweetStats.py", line 40, in <module>
    main()
  File "tweetStats.py", line 36, in main
    tweet_it(ga(cfgt()))
  File "/home/pi/tweetStats/lib/get_config.py", line 39, in get_cfgt
    cfg = js.load(data)
  File "/usr/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 22 column 5 (char 895)

See attachment for the pythonscript trowing the error. Cant find out where it goes wrong, the [ ] and ( ) and all the comma's are used correctly. Please help
![Knipsel](https://user-images.githubusercontent.com/15630050/61267187-2558fd00-a797-11e9-8e67-14f129c60414.PNG)

**Comment by mwoolweaver** [comment]
what is your development env? I'm using VScode on my iMac with Python 3.7.3 and everything works as it should.

Tweet that i just sent from my iMac below.
https://twitter.com/ComputeHole/status/1151166186622767104

**Comment by DarthKeizer** [comment]
Do you think somewthing went wrong with my dev keys from twitter?
3.7.3 (default, Apr  3 2019, 05:39:12) 
[GCC 8.2.0]

**Comment by DarthKeizer** [comment]
The error is saying that a comma is expected at line 22 column 5 in the json data, not in your python source code. I'd guess the problem is in your config.json file.

**Comment by mwoolweaver** [comment]
are you editing the right values in the config.json? Should only change the values after [line 13](https://github.com/mwoolweaver/tweetStats/blob/master/config.json.example#L13). And i can't seem to reproduce the issue at all. Can you show me what your config.json looks like minus the keys?

**Comment by mwoolweaver** [comment]
so i think i figured it out. see here


https://github.com/mwoolweaver/tweetStats/commit/3dbff170e5cb16fec2254ba9dcbad2efea4b1550

a comma on line 21 after the curly brace.

**Comment by mwoolweaver** [comment]
and also this one
https://github.com/mwoolweaver/tweetStats/commit/a8aa67cb4ac45fcf12043528ebd785f671e00f36

**Comment by mwoolweaver** [comment]
had my commas in the wrong place, sorry.

**Comment by DarthKeizer** [comment]
https://twitter.com/Halil_117/status/1151195925274120194

worked like a baws! Easy fix, man i looked at it for half an hour and I couldnt find it :)!

you can close the issue 👍

**Comment by mwoolweaver** [comment]
Thank you for the start. w/o you i wouldn't have made it this far!
