### ISSUE TITLE
cronjob running from a script

### ISSUE THREAD

**Issue by DarthKeizer** [woolweaver/tweetStats#12]
Hi there, its me again :). When a cronjob has to run multiple local scripts in Debian it cant find the rest of the file in Debian/Raspbian. I always have to make a bash script for it like the one below. If you are interested you can use it in your tweetStats 👍 .

### Cronjob 
Run: `sudo crontab -e`
Add the following line: `00 12 * * * sudo bash /home/pi/tweetStats/tweetStats.sh >> /home/pi/tweetStats/tweetStat/twitter_bot.txt 2>&1`

### Bash script tweetstats.sh
```
#!/bin/bash
cd /home/pi/tweetStats
sudo python3 /home/pi/tweetStats/tweetStats.py
cd ~


```

**Comment by DarthKeizer** [comment]
@mwoolweaver

**Comment by mwoolweaver** [comment]
That'd be a great addition. If you like you can add it yourself. You should be able to push to the repo directly as I just added you as a collaborator.
