### ISSUE TITLE
When i run your script I get the follow error

### ISSUE THREAD

**Issue by DarthKeizer** [woolweaver/tweetStats#14]
Debug Variable = 0
tweetStats.py -h for more info
[{'code': 89, 'message': 'Invalid or expired token.'}]This your down fall
[{'code': 89, 'message': 'Invalid or expired token.'}]This your down fall
Traceback (most recent call last):
  File "/home/pi/Desktop/tweetStats/tweetStats.py", line 46, in <module>
    main()
  File "/home/pi/Desktop/tweetStats/tweetStats.py", line 42, in main
    tweet_it(ga(cfgt()))
  File "/home/pi/Desktop/tweetStats/tweetStats.py", line 14, in tweet_it
    print(ga(cfgt())[3])
TypeError: 'NoneType' object is not subscriptable

I think its a typo somewhere. Will look more into it after work :)!

**Comment by mwoolweaver** [comment]
I think the error is because the login wasn't successful for some reason. 

the variable (ga(cfgt())[3]) is returned by get_api [as seen here](https://github.com/mwoolweaver/tweetStats/blob/master/lib/get_api.py#L16) is only available if login is successful.

**Comment by DarthKeizer** [comment]
I don't get it, since it works for my other script?

**Comment by mwoolweaver** [comment]
run

./tweetStats.py -dbl

**Comment by DarthKeizer** [comment]
AttributeError: 'str' object has no attribute 'OAuthHandler'
This means that he can't find OAuthHandler on a string object.

Looking at the relevant line of code:

auth = keys[4].OAuthHandler(keys[0], keys[1])
Compiler implies keys[4] is a string object.

Tracing it back, it gets keys value from cfgt()[3].

We don't have cfgt code, but anyway, you are giving it a string, and the code is trying to access OAuthHandler on a string, and there is no such thing, watcha think.

**Comment by DarthKeizer** [comment]
`python3 /home/pi/Desktop/tweetStats/tweetStats.py -dbl`
Debug Variable = 3
tweetStats.py -h for more info
[{'code': 89, 'message': 'Invalid or expired token.'}]This your down fall
Traceback (most recent call last):
  File "/home/pi/Desktop/tweetStats/tweetStats.py", line 46, in <module>
    main()
  File "/home/pi/Desktop/tweetStats/tweetStats.py", line 40, in main
    s.switch(d) 
  File "/home/pi/Desktop/tweetStats/lib/debug.py", line 29, in switch
    return getattr(self, 'case_' + str(dbm), lambda: parser.print_help())()
  File "/home/pi/Desktop/tweetStats/lib/debug.py", line 35, in case_3
    print(apiT(apiC.get_cfgt())[3])
TypeError: 'NoneType' object is not subscriptable

**Comment by mwoolweaver** [comment]
[lib/get_config.py#L31](https://github.com/mwoolweaver/tweetStats/blob/master/lib/get_config.py#L31)

it is imported here [tweetStats.py#L3](https://github.com/mwoolweaver/tweetStats/blob/master/tweetStats.py#L3)


it appears that your Twitter App isn't working... 


below is a screen shot of a successful run the -dbl flag and successful tweets sent from the latest commit on master


![Screen Shot 2019-08-03 at 11 15 35 PM](https://user-images.githubusercontent.com/5729320/62419436-b0663e00-b645-11e9-938c-acff72c02f0b.png)

**Comment by DarthKeizer** [comment]
Dude, i have no idea why it is not working. My keys work on the other script i wrote.... here is the debug message i get:

```
pi@DarthPi:~/tweetStats $ python3 tweetStats.py -db
Debug Variable = 1
tweetStats.py -h for more info

 Twitter Keys
{'consumer_key': 'VALUE2', 'consumer_secret': 'VALUE3', 'access_token': 'VALUE4', 'access_token_secret': 'VALUE5'}

Check Twitter Login
[{'code': 89, 'message': 'Invalid or expired token.'}]This your down fall
Traceback (most recent call last):
  File "tweetStats.py", line 46, in <module>
    main()
  File "tweetStats.py", line 40, in main
    s.switch(d) 
  File "/home/pi/tweetStats/lib/debug.py", line 31, in switch
    return getattr(self, 'case_' + str(dbm), lambda: parser.print_help())()
  File "/home/pi/tweetStats/lib/debug.py", line 34, in case_1
    return debug_tweet()
  File "/home/pi/tweetStats/lib/debug.py", line 65, in debug_tweet
    print(apiT(apiC.get_cfgt())[3])
TypeError: 'NoneType' object is not subscriptable
```

```
pi@DarthPi:~/tweetStats $ python3 tweetStats.py -dbp
Debug Variable = 5
tweetStats.py -h for more info
Could not contact API: Invalid URL 'VALUE1': No schema supplied. Perhaps you meant http://VALUE1?
if   == 200 --> success 

 Otherwise pi-hole URL is not configured properly. 
 Check config.json.
```

```
pi@DarthPi:~/tweetStats $ python3 tweetStats.py -dbl
Debug Variable = 3
tweetStats.py -h for more info
[{'code': 89, 'message': 'Invalid or expired token.'}]This your down fall
Traceback (most recent call last):
  File "tweetStats.py", line 46, in <module>
    main()
  File "tweetStats.py", line 40, in main
    s.switch(d) 
  File "/home/pi/tweetStats/lib/debug.py", line 31, in switch
    return getattr(self, 'case_' + str(dbm), lambda: parser.print_help())()
  File "/home/pi/tweetStats/lib/debug.py", line 36, in case_3
    print(apiT(apiC.get_cfgt())[3])
TypeError: 'NoneType' object is not subscriptable
```

pi@DarthPi:~/tweetStats $

**Comment by mwoolweaver** [comment]
It seems that the keys aren't being used at all. As the script is printing the default value (VALUE1, VALUE2, etc.)
